# Generated by Django 5.1.6 on 2025-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pick_location',
            new_name='pickup_location',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='loyalty_poins',
            new_name='loyalty_points',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='transmision',
            new_name='transmission',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit card', 'Credit Card'), ('debit card', 'Debit Card'), ('digital wallet', 'Digital Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('luxury', 'Luxury')], max_length=100),
        ),
    ]
